### PR TITLE
Song lyrics + translations

### PR DESCRIPTION
**Pull request by Seedmanc**
Hi, I've been working on completing this subtitle and retiming it for DVD release, so I thought I'd share the fruits of my work with you.

However my Japanese skills are likely to be inferior to yours so for the most part my job was about comparing several versions of online-translated japanese text with several versions of chinese and trying to figure out the meaning out of that. It probably won't pass your quality standards but it was enough to watch and understand the plot for me. In addition to that I'm not even a native English speaker myself.

For now, I'll make a PR only for the song lyrics. Those are for the most part "proper" translations in that I took them from the wiki that has the song lyrics in Japanese and English already (as the stage play CD has been released recently). However they're missing the second half of Flamingo x PPP and White Tiger songs as well as the entire PPP DoReMi song so that's where I improvised, be warned.

### CODE REVIEW

**Comment by vacaran2017** [comment]
omg I haven't checked in a while and I didn't get any email notifications, I am so sorry for the late reply.

I will take a closer look soon, hopefully (please bug me if I disappear again). It looks fine so far (still needs the original Japanese, and other autistic nitpicking).

For the song lyrics, I wonder if we should have the master transcriptions/translations be HTML files like the other songs I've [partially] done, and _then_ copy them the subtitles. I didn't realize the CD had come out (actually, I lost track of what was happening in KF because of tanoshii withdrawal and other great shit). I did get to about 1.5 songs in the subtitles, and for \~reasons\~ I was going to do the rest afterwards. (I didn't add even Youkoso Japari Park yet)

**Comment by Seedmanc** [comment]
You can probably find the japanese lyrics for songs on this site https://mojim.com/jpy182958x2x1.htm 

I didn't put them in for the well-known songs like youkoso/oozora that have "official" translations already, because I thought they're only needed for work in progress and will be gone when the subs are finished. 
I suppose it would make sense to provide subtitles and master translations separately, so that the japanese text will still be available on the site.

**Comment by Seedmanc** [comment]
Okay, so I put the japanese lyrics back into youkso and oozora, dunno what else can be helped here.
Here's your ping as well, @vacaran2017 . Wonder if that'll yield any notification at all.
I think it's about time we finish the subs for the first stage play, seeing how the second already happened.

**Comment by Seedmanc** [comment]
I've resolved the merge conflicts now, @vacaran2017

**Comment by Seedmanc** [comment]
> My hope is that this can be a general KF translation repository that is not run exclusively by me; please feel free to help out (file an issue, make a pull request, whatever it is people do on github)

**Comment by Seedmanc** [comment]
lost cause and piroko is translating this anyway

**Pull request closed without merging**
